### ISSUE TITLE
Gradle task 'createORMLiteConfigFileDebug' hangs if more than 40 @DatabaseTable's exists in project

### ISSUE THREAD

**Issue by sovaa** [stephanenicolas/ormlite-android-gradle-plugin#4]
We're noticing a slightly weird problem. On some windows machines our project stopped being able to be built when we introduced our 41st table. When building gradle will stop at createORMLiteConfigFileDebug and hang. Executing the task manually from the command line works fine and the ormlite_config.txt is generated correctly. But it is not possible to run the task in neither Intellij IDEA nor Android Studio.

If we remove the 41st @DatabaseTable class (or any @DatabaseTable class we have) it works fine. As long as it's 40 or less tables it's fine.

**Comment by stephanenicolas** [comment]
@sovaa , sorry to hear that. Nevertheless I never faced that situation. We are using the plugin with more than 40 tables without troubles, but we all have macs except some CI servers on windows..using command line.

Sorry but I don't have enough information to try anything.
